defaults:
  - _self_
  - model: md4
  - data: gmm
  - optimizer: adamw

seed: 24
device: ${oc.env:DEVICE,cuda}

train:
  steps: 20000
  batch_size: 64
  grad_clip_norm: null
  save_path: auto

log:
  every: 100

eval:
  interval: 1000
  n_samples: 20000
  log_true_distribution: true
  true_n_samples: 5000
  ckpt_path: ckpts/model.pt
  out_json: logs/metrics.json

wandb:
  enabled: true
  project: rem_sweep
  entity: 'shaojus-carnegie-mellon-university'
  group: null
