_target_: playground.models.radd.RADD

# backbone
d_model: 128
nhead: 4
d_hid: 512
n_layers: 6
dropout: 0.0

# train masking schedule
eps: 1e-3

# sampling (reverse unmasking) controls
samp_steps: 16
samp_strategy: topk     # or: vanilla
samp_k: null            # e.g., 2
#samp_k_frac: 0.2        # if set, reveal 20% of remaining per step
# samp_match_expected: true
samp_temperature: 1.0
#samp_topk_token: null   # token-level top-k; keep null for binary
