_target_: playground.models.sedd.SEDD
d_model: 128
nhead: 4
d_hid: 512
n_layers: 6
dropout: 0.0

# SEDD hyperparameters
noise_eps: 1e-3   # epsilon in sigma(t) = -log(1 - (1 - eps) * t)
t_eps: 1e-3       # keep t ∈ [t_eps, 1 - t_eps) when sampling training times
t_steps: 16      # Euler steps for reverse CTMC (sampling)
temperature: 1.0  # softmax temperature for digits during sampling
rate_scale: null  # if null, sampler uses rate_scale = L (seq length)
